### ISSUE TITLE
QUESTION: working vmware appliance

### ISSUE THREAD

**Issue by jamaisx** [LINCnil/pia#239]
Is there any working appliance? I tried to install required components and PIA on a Ubuntu VM but i was unable to run PIA due to errors invoking ng. Thanks.

**Comment by peterhuerlimann** [comment]
Not that I am aware of - maybe https://github.com/kosmas58/pia-docker (by @kosmas58 and @KillianKemps) can be of assistance?

**Comment by KillianKemps** [comment]
Hello, 
The [pia-docker](https://github.com/kosmas58/pia-docker) repository is for Docker containers so it is not the same thing as Vmware virtual machines. However, I think the `ng` errors you are encountering are not related to Vmware. 
In order to resolve your problem, we need to know what are these `ng` errors you see. Maybe these errors have already been reported in the project's [issues](https://github.com/LINCnil/pia/issues/)

**Comment by peterhuerlimann** [comment]
I know, however the containers host can easily be a VMware virtual machine, and your repo makes it easier to get up and running in contrast to fiddeling things together by hand, so I figured it might help the OP.

**Comment by kosmas58** [comment]
[VMware supports Docker containers](https://www.vmware.com/products/vsphere/integrated-containers.html).
