### ISSUE TITLE
angular2-csv is called differently from version 0.2.9 on

### ISSUE THREAD

**Issue by nwouda** [LINCnil/pia#254]
`ERROR in /pia-front/src/app/summary/summary.component.ts (7,10): Module '"/pia-front/node_modules/angular2-csv/angular2-csv"' has no exported member 'Angular2Csv'.
`

**Comment by kosmas58** [comment]
My [development branch of pia](https://github.com/kosmas58/pia) is updated to Angular 6 and uses `angular2-csv 0.29` and `save-svg-as-png 1.4.5`.

I've reworked `/src/app/summary` of pia to use the `angular2-csv` component and derived my own component from it. It brings back the Excel icon instead of the `download` text, which the `angular2-csv` component uses by default.

**Comment by LaboCNIL** [comment]
Hi @nwouda,
This issue is fixed on the master branch of pia-back and pia. We close the issue, don't hesitate to re-open it if you still encounter a problem!
