### ISSUE TITLE
Problem on exporting Report

### ISSUE THREAD

**Issue by frissner** [LINCnil/pia#595]
**Export's Word-Document is corrupted **
Export -zip contains an .odt-file in Doc-folder; 
Word 2016 says "The file is corrupt and cannot be opened"  
Word tries to repair the document and fails with "Microsoft Office cannot open this file because some parts are missing or invalid."
When opening the file with Libre Office formatting and pictures are missing and ends with 'Risks overview'; so it seems to be incomplete..

i used Pia standalone 3.0.2 (https://github.com/LINCnil/pia/releases/tag/v3.0.2)

**Pour reproduire / To Reproduce**
*Etapes pour reproduire le bug / Steps to reproduce the behavior:*
1. create a privacy impact assessment
2. select all items in "DONWLOAD ELEMENTS OF THE REPORT"
3. click download and save zip
4. extract zip 
5. navigate to Doc folder
6. open odt-file with Word 2016 -> see error messages "The file is corrupt and cannot be opened"  
7. try to repair file -> see error message "Microsoft Office cannot open this file because some parts are missing or invalid."

* i also tried to "Print the report" an selected "Microsoft Print to PDF" as printer. The resulting pdf was 0 Bytes :-(

**Comportement attendu / Expected behavior**
*Donner une description claire et concise du comportement attendu. / A clear and concise description of what you expected to happen.*
I expect a document which opens without warnings or errors

**Captures d'écran / Screenshots**
*Si pertinent, ajouter des captures d'écran pour expliquer le problème rencontré. / If applicable, add screenshots to help explain your problem.*

**Pour les versions standalones / For standalone version (please complete the following information):**
 - Système d'exploitation / OS: *[e.g. iOS]*: Windows 10 1909 64bit; Microsoft Office Professional Plus 2016 32bit  (16.0.4266.1001)
 - Version du logiciel / Software version *[e.g. 3.0.1]*: Pia standalone 3.0.2

**Pour les versions navigateurs / For browser version (please complete the following information):**
 - Système d'exploitation / OS: *[e.g. iOS]*
 - Navigateur / Browser [e.g. chrome, safari]:
 - Version du navigateur Browser version *[e.g. Edge 11]*:
 - Version du logiciel / Software version *[e.g. 3.0.1]*:

**Elements additionnels Additional context**
*Ajouter tout autre élément pertinent concernant le problème ici. / Add any other context about the problem here.*
It seems to be the case, that version 3.0.0 exports with correct formatted doc-file (no odt-file); though pictures are still missing

**Comment by syl-p** [comment]
Our developer convert .odt export into .doc export. This fixes is actualy in master branch
https://github.com/LINCnil/pia/pull/597

**Comment by kevin-atnos** [comment]
@syl-p We need to create a minor update (3.0.3) to have this fix deployed to all users.
This will solve this issue.
The patch (3.0.3) will come really soon, I will keep you in touch.

Regards,

**Comment by siben75** [comment]
Hi, I have a problem whit release 3.0.3 to print with PDFCreator 4.4.3. 
The different sections are not printed correctly because a few end of page have a row cut and divided between the two pages.
![image](https://user-images.githubusercontent.com/111377117/185067854-e83941fe-ba01-4ee2-b84c-39d2285eee02.png)

![image](https://user-images.githubusercontent.com/111377117/185068010-5a9bb4b4-f180-4158-b918-9570bdeaf69d.png)

I have tried to install on my PC Win11 and remake PDF but nothing.
I have the PIA 3.0.3 portable version installed on our server with Win Server 2012 R2 and also installed on my pc with Win 11, but the problem is the same.
I have to print the documents to sign officially and to store them in our physical archive.

To find another solution, I have tried to export the documents in .doc version to fomatted them and to apply the images exported. But the graphs are cut too.
![image](https://user-images.githubusercontent.com/111377117/185069608-7f747af5-0b22-4fe9-89f0-d6d6e61fb20c.png)

Have you ever had the same problem?
Thankyou in advance.

**Comment by syl-p** [comment]
Hello @siben75, Did you try to use the print button to get a .pdf file ? 

![image](https://github.com/LINCnil/pia/assets/50445384/d9416631-6db1-403c-9d59-838c315710d7)

Recently, we added a .pdf export option. 

This will be release very soon. 
Hope this will be helpful to you and your pdf problem.
