### ISSUE TITLE
Cannot install the front-end on the back-end debian server, instructions unclear

### ISSUE THREAD

**Issue by Philippe-Arnaud** [LINCnil/pia#64]
Hello,

I've followed the instructions provided by Bruno here: https://github.com/LINCnil/pia-back/issues/9 to install the back-end =)

Then, it seems that no instructions are available to easily install the front-end =(

Despite the critical value of PIA to drive the GDPR project in our organization, we cannot use it without a proper deployment procedure.

Could you provide a clear step by step procedure to install the whole platform on a server or provide a packaged appliance that one could deploy in a virtual environment?

The local portable version is not sufficient in our case since we have to register multiple data treatment scattered across the organization. An solo auditor would not be sufficient and we need to distribute the workload.

**Comment by kosmas58** [comment]
Hi Philippe-Arnaud, an easy way to get pia and pia-back up and running is using Docker. If included the necessary configuration files into my fork of pia and pia-back. I've also send a pull-request to LINCnil to integrate them in the official version.
Kind regards, Kosmas

**Comment by gjavault** [comment]
Hi,

help from me ?
Well ... oups ...

I bled on the subject a day or two and wrote the runbook to avoid having to
go through that again.
And since it is an opensource project, I felt I really could share my part
back.
That's why I sent you guys my runbook.

But my knowledge of the whole thing stops exactly where my runbook ends.
The dev team in my company seemed happy with the result as it was ... so I
stopped there.

Neverthelss, if you can complete the runbook with the frontend part ...
I definitly will be interrested ...


FYI to the developpers of pia (and for all the devs of the world) :
Please, for your next piece of software, write a runbook modeled on mine.
Something with the complete list of working cmdlines in order to get (fast)
a working thing right away.
Or even better : an already done small working VM (virtualbox, libvirt and
VMware format)
with a small operational guide (a few cmds ... stop, start, restart, status
... and where the files are)

If you want : I can send you guys an odt file with a few chapters as
exemples, and the styles I use to make the "cmds" and the "comments" really
stand out.



-- 

Cordialement,

Gérard


*Gérard Javault*
Ingénieur Systèmes
01 46 02 14 58
www.lafinbox.com




2018-01-30 17:53 GMT+01:00 ylachgar <notifications@github.com>:

**Comment by kosmas58** [comment]
Hi Philippe-Arnaud, pia frontend is using Angular2-CLI. So Dr. Google probably is able to help you to set up a machine. So did I to find out how to configure Docker to run pia and pia-back.

**Comment by ylachgar** [comment]
Hi back,

i am not so far to finish the things and populate to all :) but i am stuck on a point where is worrying me.
I don't know how to make available my PIA on my network.

The app work well and is accessible on my server with localhost:4200 ... now i don't know how to make it accessible to my whole company as ubuntu server isn't on the domain, any clue ?

**Comment by kosmas58** [comment]
https://github.com/angular/angular-cli/issues/1793 should give some hints to setup an IP on your server and start ng-serve with that IP.

**Comment by iouss** [comment]
Hello,

When you start ng serve ( ng serve -prod) you have a folder named dist/ , use this folder on Apache server as a web app, you can define a link to your company.
on this application you can also define the API REST server address
let me know if you want more information
Thanks

**Comment by ylachgar** [comment]
Hi All,

I guess that wasn't completely an App issue as IP configuration on Network.conf was wrong :) 
Thanks for the good help here, i am preparing the documentation for all.

**Comment by labanane34** [comment]
Hello there !

Iouss you talk about a dist/ folder, where can I find it ? I succesfully build something with this command:
`ng serve --port 8081 --host 0.0.0.0 --disable-host-check`
I can access to the PIA app but I can't find a dist/ folder with all the stuff inside. Did I miss something ? Can you tell me more ?

Best regards.

**Comment by FanchTheSystem** [comment]
@labanane34 dist folder is created when you run "ng build" command

**Comment by BoehnMa** [comment]
Try the new installation script made by ppmotskula. At least on Ubuntu 18.04 it worked for me. You can install PIA software within minutes: https://github.com/LINCnil/pia/issues/251
